CREATE USER LUCAS_OLIVEIRA IDENTIFIED BY 1234;

GRANT CREATE SESSION TO LUCAS_OLIVEIRA;

GRANT CREATE TABLE TO LUCAS_OLIVEIRA;

GRANT CREATE VIEW TO LUCAS_OLIVEIRA;

GRANT CONNECT TO LUCAS_OLIVEIRA;

GRANT RESOURCE TO LUCAS_OLIVEIRA;

GRANT UNLIMITED TABLESPACE TO LUCAS_OLIVEIRA;

GRANT ALTER USER TO LUCAS_OLIVEIRA;

GRANT DEBUG CONNECT SESSION TO LUCAS_OLIVEIRA;

GRANT DEBUG ANY PROCEDURE TO LUCAS_OLIVEIRA;

