CREATE TABLE AGENCIA (
       COD_AGENCIA NUMBER(5)    NOT NULL,
       NOME        VARCHAR2(50) NOT NULL, 
       ENDERECO    VARCHAR2(50) NULL,
       DDD_FONE    NUMBER(10)   NULL,
  CONSTRAINT PK_AGENCIA PRIMARY KEY(COD_AGENCIA));

CREATE TABLE CONTA (
       NRO_CONTA            NUMBER(14)   NOT NULL,
       COD_AGENCIA          NUMBER(5)    NOT NULL,
       NOME                 VARCHAR2(50) NOT NULL,
       SALDO                NUMBER(15,2) NOT NULL, 
       LIMITE               NUMBER(10, 2) NULL,
       ENDERECO             VARCHAR2(50) NULL,
       DDD_FONE             NUMBER(10)   NULL,
  CONSTRAINT PK_CONTA PRIMARY KEY(NRO_CONTA));

ALTER TABLE CONTA
       ADD CONSTRAINT FK_CONTA_AGENCIA 
       FOREIGN KEY (COD_AGENCIA) REFERENCES AGENCIA;

CREATE TABLE OPERACAO (
       NRO_CONTA NUMBER(14)   NOT NULL,
       DATA_OPER DATE         NOT NULL,
       DESCRICAO VARCHAR2(30) NOT NULL,
       TIPO      CHAR(1)  NOT NULL 
	             CONSTRAINT CK_OPERACAO_TIPO CHECK (TIPO IN ('D', 'C')),
       VALOR     NUMBER(15,2) NOT NULL);

ALTER TABLE OPERACAO
       ADD CONSTRAINT PK_OPERACAO PRIMARY KEY (NRO_CONTA, DATA_OPER);

-- IMPORTANTE: um campo DATE armazena Data e Hora, até a precisão dos segundos.
-- Há também o tipo TIMESTAMP, com precisão maior, pois armazena frações de segundos.

ALTER TABLE OPERACAO 
       ADD CONSTRAINT FK_OPERACAO_CONTA 
       FOREIGN KEY (NRO_CONTA) REFERENCES CONTA;

CREATE TABLE FUNDOS_INV (
       COD_FUNDO        NUMBER(2)   NOT NULL,
       NOME_FUNDO       VARCHAR2(30) NOT NULL,
   	   TAXA_ADM         NUMBER(4,2),
	      APLIC_INICIAL    NUMBER(9,2),
	      APLIC_MINIMA     NUMBER(7,2),
       TIPO_IR          CHAR(1) NOT NULL,
  CONSTRAINT PK_FUNDOS_INV PRIMARY KEY(COD_FUNDO));

CREATE TABLE FUNDOS_APLIC (
       NRO_CONTA            NUMBER(14)   NOT NULL,
       DATA_APLIC           DATE         NOT NULL,
       COD_FUNDO            NUMBER(2)    NOT NULL,
       NRO_COTAS            NUMBER(19,6) NOT NULL, 
       VLR_APLIC            NUMBER(15,2) NOT NULL, 
  CONSTRAINT PK_FUNDOS_APLIC PRIMARY KEY(NRO_CONTA, DATA_APLIC, COD_FUNDO));

ALTER TABLE FUNDOS_APLIC 
       ADD CONSTRAINT FK_FUNDOS_APLIC_CONTA 
       FOREIGN KEY (NRO_CONTA) REFERENCES CONTA;

ALTER TABLE FUNDOS_APLIC
       ADD CONSTRAINT FK_FUNDOS_APLIC_FUNDOS_INV 
       FOREIGN KEY (COD_FUNDO) REFERENCES FUNDOS_INV;

CREATE TABLE FUNDOS_COTA (
       COD_FUNDO        NUMBER(2)    NOT NULL,
       DATA_COTA            DATE         NOT NULL,
       VALOR_COTA           NUMBER(19,6) NOT NULL, 
  CONSTRAINT PK_FUNDOS_COTA PRIMARY KEY(COD_FUNDO, DATA_COTA));

ALTER TABLE FUNDOS_COTA
       ADD CONSTRAINT FK_FUNDOS_COTA_FUNDOS_INV 
       FOREIGN KEY (COD_FUNDO) REFERENCES FUNDOS_INV;

CREATE TABLE TIPO_CARTAO (
       COD_TIPO_CARTAO      NUMBER(2)    NOT NULL,
       DESCRICAO            VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_TIPO_CARTAO PRIMARY KEY(COD_TIPO_CARTAO));

CREATE TABLE CARTAO (
       NRO_CARTAO           NUMBER(16)   NOT NULL,
       NRO_CONTA            NUMBER(14)   NOT NULL,
       COD_TIPO_CARTAO      NUMBER(2)    NOT NULL,
       LIMITE               NUMBER(15,2) NOT NULL,
       DIA_VECTO            NUMBER(2)    NOT NULL,
  CONSTRAINT PK_CARTAO PRIMARY KEY(NRO_CARTAO));

ALTER TABLE CARTAO
       ADD CONSTRAINT FK_CARTAO_CONTA 
       FOREIGN KEY (NRO_CONTA) REFERENCES CONTA;

ALTER TABLE CARTAO
       ADD CONSTRAINT FK_CARTAO_TIPO_CARTAO 
       FOREIGN KEY (COD_TIPO_CARTAO) REFERENCES TIPO_CARTAO;

CREATE TABLE ESTABELECIMENTO (
       COD_ESTABELECIMENTO  NUMBER(5)   NOT NULL,
       NOME                 VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_ESTABELECIMENTO PRIMARY KEY(COD_ESTABELECIMENTO));

CREATE TABLE FATURA (
       COD_FATURA           NUMBER(15)   NOT NULL,
       NRO_CARTAO           NUMBER(16)   NOT NULL,
       DATA_VECTO           DATE         NOT NULL,
       VALOR                NUMBER(15,2) NOT NULL,
       DATA_PAGTO           DATE         NULL,
       VALOR_PAGTO          NUMBER(15,2) NULL,
  CONSTRAINT PK_FATURA PRIMARY KEY(COD_FATURA));

ALTER TABLE FATURA
       ADD CONSTRAINT FK_FATURA_CARTAO
       FOREIGN KEY (NRO_CARTAO) REFERENCES CARTAO;

CREATE TABLE MOVTO_CARTAO (
       NRO_CARTAO           NUMBER(16)   NOT NULL,
       DATA_MOVTO           DATE         NOT NULL,
       COD_ESTABELECIMENTO  NUMBER(5)    NOT NULL,
       VALOR                NUMBER(15,2) NOT NULL,
       COD_FATURA           NUMBER(15)   NULL,
  CONSTRAINT PK_MOVTO_CARTAO PRIMARY KEY(NRO_CARTAO, DATA_MOVTO));

ALTER TABLE MOVTO_CARTAO
       ADD CONSTRAINT FK_MOVTO_CARTAO_CARTAO
       FOREIGN KEY (NRO_CARTAO) REFERENCES CARTAO;

ALTER TABLE MOVTO_CARTAO
       ADD CONSTRAINT FK_MOVTO_CARTAO_ESTAB
       FOREIGN KEY (COD_ESTABELECIMENTO) REFERENCES ESTABELECIMENTO;

ALTER TABLE MOVTO_CARTAO
       ADD CONSTRAINT FK_MOVTO_CARTAO_FATURA
       FOREIGN KEY (COD_FATURA) REFERENCES FATURA;

CREATE TABLE ALIQUOTAS_IR (
  TIPO_IR  CHAR(1)     NOT NULL,
  DIAS_DE  NUMBER(3)   NOT NULL,
  DIAS_ATE NUMBER(5)   NOT NULL,
  ALIQUOTA NUMBER(3,1) NOT NULL,
  CONSTRAINT PK_ALIQUOTA_IR PRIMARY KEY (TIPO_IR, DIAS_DE));
